version: '3.8'

services:
  dev:
    image: node:21
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    #stdin_open: true
    #tty: true

  prod:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
